[package]
name = "wasm_to_png"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.1"
base64 = "0.22.0"
oxipng = "9.0.0"
